# nixpacks.toml
[phases.setup]
nixPkgs = ['nodejs_20', 'php82']

[phases.install]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-scripts --no-interaction',
    'npm cache clean --force || true',
    'rm -rf node_modules package-lock.json || true',
    'npm install --legacy-peer-deps --no-audit --no-fund --include=optional',
    'npm install @rollup/rollup-linux-x64-gnu --save-optional --legacy-peer-deps || true'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:clear || true',
    'php artisan route:clear || true', 
    'php artisan view:clear || true',
    'php artisan cache:clear || true',
    'php artisan config:cache || true',
    'php artisan route:cache || true',
    'php artisan view:cache || true'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'